name: Docker Image CI

on: 
  push:
    paths: 
      - "poetry.lock"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Export requirement
      run: cd .container && poetry export -f requirements.txt > requirements.txt && cd ..
    - name: Build the Docker image
      run: cd .container && docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/procgen_adventure
    - name: Pushing Docker container to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin  && docker push ${{ secrets.DOCKER_USERNAME }}/procgen_adventure
    - name: Post status to Discord
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        job: Build docker image
