name: Unit tests CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip setuptools
        pip install poetry
        poetry install
    - name: Run test
      run: poetry run pytest --cov=procgen_adventure
    - name: Post status on Discord
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        job: Running unit tests
